% personajes.pl - AUTO-GENERADO por generate.py. NO EDITAR.

atributo(mickey_mouse, especie, animal).
atributo(mickey_mouse, es_villano, no).
atributo(mickey_mouse, es_protagonista, si).
atributo(mickey_mouse, color_pelo, negro).
atributo(mickey_mouse, pelo, corto).
atributo(mickey_mouse, es_magico, no).
atributo(mickey_mouse, color_vestimenta, rojo).
atributo(mickey_mouse, vive_en, ciudad).
atributo(mickey_mouse, genero, masculino).
atributo(mickey_mouse, habla, si).

atributo(minnie_mouse, especie, animal).
atributo(minnie_mouse, es_villano, no).
atributo(minnie_mouse, es_protagonista, si).
atributo(minnie_mouse, color_pelo, negro).
atributo(minnie_mouse, pelo, corto).
atributo(minnie_mouse, es_magico, no).
atributo(minnie_mouse, color_vestimenta, rosa).
atributo(minnie_mouse, vive_en, ciudad).
atributo(minnie_mouse, genero, femenino).
atributo(minnie_mouse, habla, si).

atributo(daisy_duck, especie, animal).
atributo(daisy_duck, es_villano, no).
atributo(daisy_duck, es_protagonista, si).
atributo(daisy_duck, color_pelo, ninguno).
atributo(daisy_duck, pelo, sin_pelo).
atributo(daisy_duck, es_magico, no).
atributo(daisy_duck, color_vestimenta, morado).
atributo(daisy_duck, vive_en, ciudad).
atributo(daisy_duck, genero, femenino).
atributo(daisy_duck, habla, si).

atributo(donald_duck, especie, animal).
atributo(donald_duck, es_villano, no).
atributo(donald_duck, es_protagonista, si).
atributo(donald_duck, color_pelo, ninguno).
atributo(donald_duck, pelo, sin_pelo).
atributo(donald_duck, es_magico, no).
atributo(donald_duck, color_vestimenta, azul).
atributo(donald_duck, vive_en, ciudad).
atributo(donald_duck, genero, masculino).
atributo(donald_duck, habla, si).

atributo(goofy, especie, animal).
atributo(goofy, es_villano, no).
atributo(goofy, es_protagonista, si).
atributo(goofy, color_pelo, negro).
atributo(goofy, pelo, corto).
atributo(goofy, es_magico, no).
atributo(goofy, color_vestimenta, naranja).
atributo(goofy, vive_en, ciudad).
atributo(goofy, genero, masculino).
atributo(goofy, habla, si).

atributo(pluto, especie, animal).
atributo(pluto, es_villano, no).
atributo(pluto, es_protagonista, no).
atributo(pluto, color_pelo, rubio).
atributo(pluto, pelo, corto).
atributo(pluto, es_magico, no).
atributo(pluto, color_vestimenta, verde).
atributo(pluto, vive_en, ciudad).
atributo(pluto, genero, masculino).
atributo(pluto, habla, no).

atributo(aladdin, especie, humano).
atributo(aladdin, es_villano, no).
atributo(aladdin, es_protagonista, si).
atributo(aladdin, color_pelo, negro).
atributo(aladdin, pelo, corto).
atributo(aladdin, es_magico, no).
atributo(aladdin, color_vestimenta, blanco).
atributo(aladdin, vive_en, desierto).
atributo(aladdin, genero, masculino).
atributo(aladdin, habla, si).

atributo(jasmine, especie, humano).
atributo(jasmine, es_villano, no).
atributo(jasmine, es_protagonista, si).
atributo(jasmine, color_pelo, negro).
atributo(jasmine, pelo, largo).
atributo(jasmine, es_magico, no).
atributo(jasmine, color_vestimenta, verde).
atributo(jasmine, vive_en, desierto).
atributo(jasmine, genero, femenino).
atributo(jasmine, habla, si).

atributo(alice, especie, humano).
atributo(alice, es_villano, no).
atributo(alice, es_protagonista, si).
atributo(alice, color_pelo, rubio).
atributo(alice, pelo, largo).
atributo(alice, es_magico, no).
atributo(alice, color_vestimenta, azul).
atributo(alice, vive_en, otro).
atributo(alice, genero, femenino).
atributo(alice, habla, si).

atributo(cheshire_cat, especie, animal).
atributo(cheshire_cat, es_villano, no).
atributo(cheshire_cat, es_protagonista, no).
atributo(cheshire_cat, color_pelo, morado).
atributo(cheshire_cat, pelo, corto).
atributo(cheshire_cat, es_magico, si).
atributo(cheshire_cat, color_vestimenta, na).
atributo(cheshire_cat, vive_en, bosque).
atributo(cheshire_cat, genero, masculino).
atributo(cheshire_cat, habla, si).

atributo(white_rabbit, especie, animal).
atributo(white_rabbit, es_villano, no).
atributo(white_rabbit, es_protagonista, no).
atributo(white_rabbit, color_pelo, blanco).
atributo(white_rabbit, pelo, corto).
atributo(white_rabbit, es_magico, no).
atributo(white_rabbit, color_vestimenta, cafe).
atributo(white_rabbit, vive_en, otro).
atributo(white_rabbit, genero, masculino).
atributo(white_rabbit, habla, si).

atributo(genie, especie, ser_magico).
atributo(genie, es_villano, no).
atributo(genie, es_protagonista, si).
atributo(genie, color_pelo, negro).
atributo(genie, pelo, largo).
atributo(genie, es_magico, si).
atributo(genie, color_vestimenta, azul).
atributo(genie, vive_en, desierto).
atributo(genie, genero, masculino).
atributo(genie, habla, si).

atributo(dutchess, especie, animal).
atributo(dutchess, es_villano, no).
atributo(dutchess, es_protagonista, no).
atributo(dutchess, color_pelo, blanco).
atributo(dutchess, pelo, corto).
atributo(dutchess, es_magico, no).
atributo(dutchess, color_vestimenta, na).
atributo(dutchess, vive_en, ciudad).
atributo(dutchess, genero, femenino).
atributo(dutchess, habla, si).

atributo(omalley, especie, animal).
atributo(omalley, es_villano, no).
atributo(omalley, es_protagonista, si).
atributo(omalley, color_pelo, naranja).
atributo(omalley, pelo, corto).
atributo(omalley, es_magico, no).
atributo(omalley, color_vestimenta, na).
atributo(omalley, vive_en, ciudad).
atributo(omalley, genero, masculino).
atributo(omalley, habla, si).

atributo(marie, especie, animal).
atributo(marie, es_villano, no).
atributo(marie, es_protagonista, si).
atributo(marie, color_pelo, blanco).
atributo(marie, pelo, corto).
atributo(marie, es_magico, no).
atributo(marie, color_vestimenta, rosa).
atributo(marie, vive_en, ciudad).
atributo(marie, genero, femenino).
atributo(marie, habla, si).

atributo(pinocchio, especie, objeto).
atributo(pinocchio, es_villano, no).
atributo(pinocchio, es_protagonista, si).
atributo(pinocchio, color_pelo, negro).
atributo(pinocchio, pelo, corto).
atributo(pinocchio, es_magico, si).
atributo(pinocchio, color_vestimenta, rojo).
atributo(pinocchio, vive_en, ciudad).
atributo(pinocchio, genero, masculino).
atributo(pinocchio, habla, si).

atributo(jiminy_cricket, especie, insecto).
atributo(jiminy_cricket, es_villano, no).
atributo(jiminy_cricket, es_protagonista, si).
atributo(jiminy_cricket, color_pelo, negro).
atributo(jiminy_cricket, pelo, corto).
atributo(jiminy_cricket, es_magico, no).
atributo(jiminy_cricket, color_vestimenta, negro).
atributo(jiminy_cricket, vive_en, otro).
atributo(jiminy_cricket, genero, masculino).
atributo(jiminy_cricket, habla, si).

atributo(pocahontas, especie, humano).
atributo(pocahontas, es_villano, no).
atributo(pocahontas, es_protagonista, si).
atributo(pocahontas, color_pelo, negro).
atributo(pocahontas, pelo, largo).
atributo(pocahontas, es_magico, no).
atributo(pocahontas, color_vestimenta, cafe).
atributo(pocahontas, vive_en, bosque).
atributo(pocahontas, genero, femenino).
atributo(pocahontas, habla, si).

atributo(john_smith, especie, humano).
atributo(john_smith, es_villano, no).
atributo(john_smith, es_protagonista, si).
atributo(john_smith, color_pelo, rubio).
atributo(john_smith, pelo, corto).
atributo(john_smith, es_magico, no).
atributo(john_smith, color_vestimenta, azul).
atributo(john_smith, vive_en, bosque).
atributo(john_smith, genero, masculino).
atributo(john_smith, habla, si).

atributo(tinkerbell, especie, ser_magico).
atributo(tinkerbell, es_villano, no).
atributo(tinkerbell, es_protagonista, si).
atributo(tinkerbell, color_pelo, rubio).
atributo(tinkerbell, pelo, corto).
atributo(tinkerbell, es_magico, si).
atributo(tinkerbell, color_vestimenta, verde).
atributo(tinkerbell, vive_en, bosque).
atributo(tinkerbell, genero, femenino).
atributo(tinkerbell, habla, si).

atributo(prince_naveen, especie, humano).
atributo(prince_naveen, es_villano, no).
atributo(prince_naveen, es_protagonista, si).
atributo(prince_naveen, color_pelo, negro).
atributo(prince_naveen, pelo, corto).
atributo(prince_naveen, es_magico, no).
atributo(prince_naveen, color_vestimenta, verde).
atributo(prince_naveen, vive_en, otro).
atributo(prince_naveen, genero, masculino).
atributo(prince_naveen, habla, si).

atributo(tiana, especie, humano).
atributo(tiana, es_villano, no).
atributo(tiana, es_protagonista, si).
atributo(tiana, color_pelo, negro).
atributo(tiana, pelo, largo).
atributo(tiana, es_magico, no).
atributo(tiana, color_vestimenta, verde).
atributo(tiana, vive_en, ciudad).
atributo(tiana, genero, femenino).
atributo(tiana, habla, si).

atributo(ray, especie, insecto).
atributo(ray, es_villano, no).
atributo(ray, es_protagonista, no).
atributo(ray, color_pelo, negro).
atributo(ray, pelo, corto).
atributo(ray, es_magico, no).
atributo(ray, color_vestimenta, na).
atributo(ray, vive_en, pantano).
atributo(ray, genero, masculino).
atributo(ray, habla, si).

atributo(louis, especie, animal).
atributo(louis, es_villano, no).
atributo(louis, es_protagonista, no).
atributo(louis, color_pelo, ninguno).
atributo(louis, pelo, sin_pelo).
atributo(louis, es_magico, no).
atributo(louis, color_vestimenta, na).
atributo(louis, vive_en, pantano).
atributo(louis, genero, masculino).
atributo(louis, habla, si).

atributo(robin_hood, especie, animal).
atributo(robin_hood, es_villano, no).
atributo(robin_hood, es_protagonista, si).
atributo(robin_hood, color_pelo, rojo).
atributo(robin_hood, pelo, corto).
atributo(robin_hood, es_magico, no).
atributo(robin_hood, color_vestimenta, verde).
atributo(robin_hood, vive_en, bosque).
atributo(robin_hood, genero, masculino).
atributo(robin_hood, habla, si).

atributo(maid_marian, especie, animal).
atributo(maid_marian, es_villano, no).
atributo(maid_marian, es_protagonista, si).
atributo(maid_marian, color_pelo, rojo).
atributo(maid_marian, pelo, corto).
atributo(maid_marian, es_magico, no).
atributo(maid_marian, color_vestimenta, morado).
atributo(maid_marian, vive_en, bosque).
atributo(maid_marian, genero, femenino).
atributo(maid_marian, habla, si).

atributo(little_john, especie, animal).
atributo(little_john, es_villano, no).
atributo(little_john, es_protagonista, si).
atributo(little_john, color_pelo, cafe).
atributo(little_john, pelo, corto).
atributo(little_john, es_magico, no).
atributo(little_john, color_vestimenta, verde).
atributo(little_john, vive_en, bosque).
atributo(little_john, genero, masculino).
atributo(little_john, habla, si).

atributo(prince_phillip, especie, humano).
atributo(prince_phillip, es_villano, no).
atributo(prince_phillip, es_protagonista, si).
atributo(prince_phillip, color_pelo, cafe).
atributo(prince_phillip, pelo, corto).
atributo(prince_phillip, es_magico, no).
atributo(prince_phillip, color_vestimenta, negro).
atributo(prince_phillip, vive_en, castillo).
atributo(prince_phillip, genero, masculino).
atributo(prince_phillip, habla, si).

atributo(aurora, especie, humano).
atributo(aurora, es_villano, no).
atributo(aurora, es_protagonista, si).
atributo(aurora, color_pelo, rubio).
atributo(aurora, pelo, largo).
atributo(aurora, es_magico, no).
atributo(aurora, color_vestimenta, rosa).
atributo(aurora, vive_en, castillo).
atributo(aurora, genero, femenino).
atributo(aurora, habla, si).

atributo(fauna, especie, ser_magico).
atributo(fauna, es_villano, no).
atributo(fauna, es_protagonista, no).
atributo(fauna, color_pelo, gris).
atributo(fauna, pelo, corto).
atributo(fauna, es_magico, si).
atributo(fauna, color_vestimenta, verde).
atributo(fauna, vive_en, castillo).
atributo(fauna, genero, femenino).
atributo(fauna, habla, si).

atributo(flora, especie, ser_magico).
atributo(flora, es_villano, no).
atributo(flora, es_protagonista, no).
atributo(flora, color_pelo, gris).
atributo(flora, pelo, corto).
atributo(flora, es_magico, si).
atributo(flora, color_vestimenta, rojo).
atributo(flora, vive_en, bosque).
atributo(flora, genero, femenino).
atributo(flora, habla, si).

atributo(merriweather, especie, ser_magico).
atributo(merriweather, es_villano, no).
atributo(merriweather, es_protagonista, no).
atributo(merriweather, color_pelo, negro).
atributo(merriweather, pelo, corto).
atributo(merriweather, es_magico, si).
atributo(merriweather, color_vestimenta, azul).
atributo(merriweather, vive_en, bosque).
atributo(merriweather, genero, femenino).
atributo(merriweather, habla, si).

atributo(snow_white, especie, humano).
atributo(snow_white, es_villano, no).
atributo(snow_white, es_protagonista, si).
atributo(snow_white, color_pelo, negro).
atributo(snow_white, pelo, corto).
atributo(snow_white, es_magico, no).
atributo(snow_white, color_vestimenta, amarillo).
atributo(snow_white, vive_en, bosque).
atributo(snow_white, genero, femenino).
atributo(snow_white, habla, si).

atributo(doc, especie, ser_magico).
atributo(doc, es_villano, no).
atributo(doc, es_protagonista, no).
atributo(doc, color_pelo, blanco).
atributo(doc, pelo, corto).
atributo(doc, es_magico, no).
atributo(doc, color_vestimenta, naranja).
atributo(doc, vive_en, bosque).
atributo(doc, genero, masculino).
atributo(doc, habla, si).

atributo(dopey, especie, ser_magico).
atributo(dopey, es_villano, no).
atributo(dopey, es_protagonista, no).
atributo(dopey, color_pelo, blanco).
atributo(dopey, pelo, corto).
atributo(dopey, es_magico, no).
atributo(dopey, color_vestimenta, verde).
atributo(dopey, vive_en, bosque).
atributo(dopey, genero, masculino).
atributo(dopey, habla, si).

atributo(sleepy, especie, ser_magico).
atributo(sleepy, es_villano, no).
atributo(sleepy, es_protagonista, no).
atributo(sleepy, color_pelo, blanco).
atributo(sleepy, pelo, corto).
atributo(sleepy, es_magico, no).
atributo(sleepy, color_vestimenta, cafe).
atributo(sleepy, vive_en, bosque).
atributo(sleepy, genero, masculino).
atributo(sleepy, habla, si).

atributo(sneezy, especie, ser_magico).
atributo(sneezy, es_villano, no).
atributo(sneezy, es_protagonista, no).
atributo(sneezy, color_pelo, blanco).
atributo(sneezy, pelo, corto).
atributo(sneezy, es_magico, no).
atributo(sneezy, color_vestimenta, amarillo).
atributo(sneezy, vive_en, bosque).
atributo(sneezy, genero, masculino).
atributo(sneezy, habla, si).

atributo(happy, especie, ser_magico).
atributo(happy, es_villano, no).
atributo(happy, es_protagonista, no).
atributo(happy, color_pelo, blanco).
atributo(happy, pelo, corto).
atributo(happy, es_magico, no).
atributo(happy, color_vestimenta, azul).
atributo(happy, vive_en, bosque).
atributo(happy, genero, masculino).
atributo(happy, habla, si).

atributo(bashful, especie, ser_magico).
atributo(bashful, es_villano, no).
atributo(bashful, es_protagonista, no).
atributo(bashful, color_pelo, blanco).
atributo(bashful, pelo, largo).
atributo(bashful, es_magico, no).
atributo(bashful, color_vestimenta, cafe).
atributo(bashful, vive_en, bosque).
atributo(bashful, genero, masculino).
atributo(bashful, habla, si).

atributo(grumpy, especie, ser_magico).
atributo(grumpy, es_villano, no).
atributo(grumpy, es_protagonista, no).
atributo(grumpy, color_pelo, blanco).
atributo(grumpy, pelo, corto).
atributo(grumpy, es_magico, no).
atributo(grumpy, color_vestimenta, rojo).
atributo(grumpy, vive_en, bosque).
atributo(grumpy, genero, masculino).
atributo(grumpy, habla, si).

atributo(rapunzel, especie, humano).
atributo(rapunzel, es_villano, no).
atributo(rapunzel, es_protagonista, si).
atributo(rapunzel, color_pelo, rubio).
atributo(rapunzel, pelo, largo).
atributo(rapunzel, es_magico, si).
atributo(rapunzel, color_vestimenta, morado).
atributo(rapunzel, vive_en, bosque).
atributo(rapunzel, genero, femenino).
atributo(rapunzel, habla, si).

atributo(eugene, especie, humano).
atributo(eugene, es_villano, no).
atributo(eugene, es_protagonista, no).
atributo(eugene, color_pelo, cafe).
atributo(eugene, pelo, corto).
atributo(eugene, es_magico, no).
atributo(eugene, color_vestimenta, azul).
atributo(eugene, vive_en, ciudad).
atributo(eugene, genero, masculino).
atributo(eugene, habla, si).

atributo(tarzan, especie, humano).
atributo(tarzan, es_villano, no).
atributo(tarzan, es_protagonista, si).
atributo(tarzan, color_pelo, cafe).
atributo(tarzan, pelo, largo).
atributo(tarzan, es_magico, no).
atributo(tarzan, color_vestimenta, cafe).
atributo(tarzan, vive_en, bosque).
atributo(tarzan, genero, masculino).
atributo(tarzan, habla, si).

atributo(jane, especie, humano).
atributo(jane, es_villano, no).
atributo(jane, es_protagonista, no).
atributo(jane, color_pelo, cafe).
atributo(jane, pelo, largo).
atributo(jane, es_magico, no).
atributo(jane, color_vestimenta, amarillo).
atributo(jane, vive_en, ciudad).
atributo(jane, genero, femenino).
atributo(jane, habla, si).

atributo(woody, especie, objeto).
atributo(woody, es_villano, no).
atributo(woody, es_protagonista, si).
atributo(woody, color_pelo, cafe).
atributo(woody, pelo, corto).
atributo(woody, es_magico, no).
atributo(woody, color_vestimenta, amarillo).
atributo(woody, vive_en, ciudad).
atributo(woody, genero, masculino).
atributo(woody, habla, si).

atributo(dash, especie, humano).
atributo(dash, es_villano, no).
atributo(dash, es_protagonista, si).
atributo(dash, color_pelo, rubio).
atributo(dash, pelo, corto).
atributo(dash, es_magico, si).
atributo(dash, color_vestimenta, rojo).
atributo(dash, vive_en, ciudad).
atributo(dash, genero, masculino).
atributo(dash, habla, si).

atributo(jack_jack, especie, humano).
atributo(jack_jack, es_villano, no).
atributo(jack_jack, es_protagonista, no).
atributo(jack_jack, color_pelo, rubio).
atributo(jack_jack, pelo, corto).
atributo(jack_jack, es_magico, si).
atributo(jack_jack, color_vestimenta, rojo).
atributo(jack_jack, vive_en, ciudad).
atributo(jack_jack, genero, masculino).
atributo(jack_jack, habla, si).

atributo(mowgli, especie, humano).
atributo(mowgli, es_villano, no).
atributo(mowgli, es_protagonista, si).
atributo(mowgli, color_pelo, negro).
atributo(mowgli, pelo, corto).
atributo(mowgli, es_magico, no).
atributo(mowgli, color_vestimenta, rojo).
atributo(mowgli, vive_en, selva).
atributo(mowgli, genero, masculino).
atributo(mowgli, habla, si).

atributo(baloo, especie, animal).
atributo(baloo, es_villano, no).
atributo(baloo, es_protagonista, si).
atributo(baloo, color_pelo, gris).
atributo(baloo, pelo, corto).
atributo(baloo, es_magico, no).
atributo(baloo, color_vestimenta, na).
atributo(baloo, vive_en, selva).
atributo(baloo, genero, masculino).
atributo(baloo, habla, si).

atributo(bagheera, especie, animal).
atributo(bagheera, es_villano, no).
atributo(bagheera, es_protagonista, no).
atributo(bagheera, color_pelo, negro).
atributo(bagheera, pelo, corto).
atributo(bagheera, es_magico, no).
atributo(bagheera, color_vestimenta, na).
atributo(bagheera, vive_en, selva).
atributo(bagheera, genero, masculino).
atributo(bagheera, habla, si).

atributo(tramp, especie, animal).
atributo(tramp, es_villano, no).
atributo(tramp, es_protagonista, si).
atributo(tramp, color_pelo, gris).
atributo(tramp, pelo, corto).
atributo(tramp, es_magico, no).
atributo(tramp, color_vestimenta, rojo).
atributo(tramp, vive_en, ciudad).
atributo(tramp, genero, masculino).
atributo(tramp, habla, si).

atributo(lady, especie, animal).
atributo(lady, es_villano, no).
atributo(lady, es_protagonista, si).
atributo(lady, color_pelo, naranja).
atributo(lady, pelo, largo).
atributo(lady, es_magico, no).
atributo(lady, color_vestimenta, azul).
atributo(lady, vive_en, ciudad).
atributo(lady, genero, femenino).
atributo(lady, habla, si).

atributo(lilo, especie, humano).
atributo(lilo, es_villano, no).
atributo(lilo, es_protagonista, si).
atributo(lilo, color_pelo, negro).
atributo(lilo, pelo, largo).
atributo(lilo, es_magico, no).
atributo(lilo, color_vestimenta, rojo).
atributo(lilo, vive_en, ciudad).
atributo(lilo, genero, femenino).
atributo(lilo, habla, si).

atributo(stitch, especie, animal).
atributo(stitch, es_villano, no).
atributo(stitch, es_protagonista, si).
atributo(stitch, color_pelo, azul).
atributo(stitch, pelo, corto).
atributo(stitch, es_magico, no).
atributo(stitch, color_vestimenta, na).
atributo(stitch, vive_en, otro).
atributo(stitch, genero, masculino).
atributo(stitch, habla, si).

atributo(simba, especie, animal).
atributo(simba, es_villano, no).
atributo(simba, es_protagonista, si).
atributo(simba, color_pelo, rubio).
atributo(simba, pelo, corto).
atributo(simba, es_magico, no).
atributo(simba, color_vestimenta, na).
atributo(simba, vive_en, desierto).
atributo(simba, genero, masculino).
atributo(simba, habla, si).

atributo(nala, especie, animal).
atributo(nala, es_villano, no).
atributo(nala, es_protagonista, no).
atributo(nala, color_pelo, rubio).
atributo(nala, pelo, corto).
atributo(nala, es_magico, no).
atributo(nala, color_vestimenta, na).
atributo(nala, vive_en, desierto).
atributo(nala, genero, masculino).
atributo(nala, habla, si).

atributo(timon, especie, animal).
atributo(timon, es_villano, no).
atributo(timon, es_protagonista, no).
atributo(timon, color_pelo, naranja).
atributo(timon, pelo, corto).
atributo(timon, es_magico, no).
atributo(timon, color_vestimenta, na).
atributo(timon, vive_en, desierto).
atributo(timon, genero, masculino).
atributo(timon, habla, si).

atributo(pumbaa, especie, animal).
atributo(pumbaa, es_villano, no).
atributo(pumbaa, es_protagonista, no).
atributo(pumbaa, color_pelo, rojo).
atributo(pumbaa, pelo, corto).
atributo(pumbaa, es_magico, no).
atributo(pumbaa, color_vestimenta, na).
atributo(pumbaa, vive_en, desierto).
atributo(pumbaa, genero, masculino).
atributo(pumbaa, habla, si).

atributo(rafiki, especie, animal).
atributo(rafiki, es_villano, no).
atributo(rafiki, es_protagonista, no).
atributo(rafiki, color_pelo, gris).
atributo(rafiki, pelo, corto).
atributo(rafiki, es_magico, no).
atributo(rafiki, color_vestimenta, na).
atributo(rafiki, vive_en, desierto).
atributo(rafiki, genero, masculino).
atributo(rafiki, habla, si).

atributo(zazu, especie, animal).
atributo(zazu, es_villano, no).
atributo(zazu, es_protagonista, no).
atributo(zazu, color_pelo, azul).
atributo(zazu, pelo, corto).
atributo(zazu, es_magico, no).
atributo(zazu, color_vestimenta, na).
atributo(zazu, vive_en, desierto).
atributo(zazu, genero, masculino).
atributo(zazu, habla, si).

atributo(buzz_lightyear, especie, objeto).
atributo(buzz_lightyear, es_villano, no).
atributo(buzz_lightyear, es_protagonista, si).
atributo(buzz_lightyear, color_pelo, cafe).
atributo(buzz_lightyear, pelo, corto).
atributo(buzz_lightyear, es_magico, no).
atributo(buzz_lightyear, color_vestimenta, blanco).
atributo(buzz_lightyear, vive_en, otro).
atributo(buzz_lightyear, genero, masculino).
atributo(buzz_lightyear, habla, si).

atributo(rex, especie, objeto).
atributo(rex, es_villano, no).
atributo(rex, es_protagonista, no).
atributo(rex, color_pelo, ninguno).
atributo(rex, pelo, sin_pelo).
atributo(rex, es_magico, no).
atributo(rex, color_vestimenta, verde).
atributo(rex, vive_en, otro).
atributo(rex, genero, masculino).
atributo(rex, habla, si).

atributo(ham, especie, objeto).
atributo(ham, es_villano, no).
atributo(ham, es_protagonista, no).
atributo(ham, color_pelo, ninguno).
atributo(ham, pelo, sin_pelo).
atributo(ham, es_magico, no).
atributo(ham, color_vestimenta, rosa).
atributo(ham, vive_en, otro).
atributo(ham, genero, masculino).
atributo(ham, habla, si).

atributo(slinky, especie, objeto).
atributo(slinky, es_villano, no).
atributo(slinky, es_protagonista, no).
atributo(slinky, color_pelo, ninguno).
atributo(slinky, pelo, sin_pelo).
atributo(slinky, es_magico, no).
atributo(slinky, color_vestimenta, cafe).
atributo(slinky, vive_en, otro).
atributo(slinky, genero, masculino).
atributo(slinky, habla, si).

atributo(bullseye, especie, objeto).
atributo(bullseye, es_villano, no).
atributo(bullseye, es_protagonista, no).
atributo(bullseye, color_pelo, ninguno).
atributo(bullseye, pelo, sin_pelo).
atributo(bullseye, es_magico, no).
atributo(bullseye, color_vestimenta, cafe).
atributo(bullseye, vive_en, otro).
atributo(bullseye, genero, masculino).
atributo(bullseye, habla, no).

atributo(jesse, especie, objeto).
atributo(jesse, es_villano, no).
atributo(jesse, es_protagonista, si).
atributo(jesse, color_pelo, rojo).
atributo(jesse, pelo, largo).
atributo(jesse, es_magico, no).
atributo(jesse, color_vestimenta, azul).
atributo(jesse, vive_en, otro).
atributo(jesse, genero, femenino).
atributo(jesse, habla, si).

atributo(mr_potatohead, especie, objeto).
atributo(mr_potatohead, es_villano, no).
atributo(mr_potatohead, es_protagonista, si).
atributo(mr_potatohead, color_pelo, negro).
atributo(mr_potatohead, pelo, corto).
atributo(mr_potatohead, es_magico, no).
atributo(mr_potatohead, color_vestimenta, na).
atributo(mr_potatohead, vive_en, otro).
atributo(mr_potatohead, genero, masculino).
atributo(mr_potatohead, habla, si).

atributo(ralph, especie, humano).
atributo(ralph, es_villano, no).
atributo(ralph, es_protagonista, si).
atributo(ralph, color_pelo, cafe).
atributo(ralph, pelo, corto).
atributo(ralph, es_magico, no).
atributo(ralph, color_vestimenta, naranja).
atributo(ralph, vive_en, ciudad).
atributo(ralph, genero, masculino).
atributo(ralph, habla, si).

atributo(vanelope, especie, humano).
atributo(vanelope, es_villano, no).
atributo(vanelope, es_protagonista, si).
atributo(vanelope, color_pelo, negro).
atributo(vanelope, pelo, largo).
atributo(vanelope, es_magico, no).
atributo(vanelope, color_vestimenta, verde).
atributo(vanelope, vive_en, otro).
atributo(vanelope, genero, femenino).
atributo(vanelope, habla, si).

atributo(felix, especie, humano).
atributo(felix, es_villano, no).
atributo(felix, es_protagonista, si).
atributo(felix, color_pelo, cafe).
atributo(felix, pelo, corto).
atributo(felix, es_magico, si).
atributo(felix, color_vestimenta, azul).
atributo(felix, vive_en, otro).
atributo(felix, genero, masculino).
atributo(felix, habla, si).

atributo(winnie_the_pooh, especie, animal).
atributo(winnie_the_pooh, es_villano, no).
atributo(winnie_the_pooh, es_protagonista, si).
atributo(winnie_the_pooh, color_pelo, ninguno).
atributo(winnie_the_pooh, pelo, sin_pelo).
atributo(winnie_the_pooh, es_magico, no).
atributo(winnie_the_pooh, color_vestimenta, rojo).
atributo(winnie_the_pooh, vive_en, bosque).
atributo(winnie_the_pooh, genero, masculino).
atributo(winnie_the_pooh, habla, si).

atributo(piglet, especie, animal).
atributo(piglet, es_villano, no).
atributo(piglet, es_protagonista, si).
atributo(piglet, color_pelo, ninguno).
atributo(piglet, pelo, sin_pelo).
atributo(piglet, es_magico, no).
atributo(piglet, color_vestimenta, rosa).
atributo(piglet, vive_en, bosque).
atributo(piglet, genero, masculino).
atributo(piglet, habla, si).

atributo(eeyore, especie, animal).
atributo(eeyore, es_villano, no).
atributo(eeyore, es_protagonista, no).
atributo(eeyore, color_pelo, negro).
atributo(eeyore, pelo, corto).
atributo(eeyore, es_magico, no).
atributo(eeyore, color_vestimenta, gris).
atributo(eeyore, vive_en, bosque).
atributo(eeyore, genero, masculino).
atributo(eeyore, habla, si).

atributo(rabbit, especie, animal).
atributo(rabbit, es_villano, no).
atributo(rabbit, es_protagonista, no).
atributo(rabbit, color_pelo, blanco).
atributo(rabbit, pelo, corto).
atributo(rabbit, es_magico, no).
atributo(rabbit, color_vestimenta, amarillo).
atributo(rabbit, vive_en, bosque).
atributo(rabbit, genero, masculino).
atributo(rabbit, habla, si).

atributo(tigger, especie, animal).
atributo(tigger, es_villano, no).
atributo(tigger, es_protagonista, no).
atributo(tigger, color_pelo, ninguno).
atributo(tigger, pelo, sin_pelo).
atributo(tigger, es_magico, no).
atributo(tigger, color_vestimenta, naranja).
atributo(tigger, vive_en, bosque).
atributo(tigger, genero, masculino).
atributo(tigger, habla, si).

atributo(berlioz, especie, animal).
atributo(berlioz, es_villano, no).
atributo(berlioz, es_protagonista, no).
atributo(berlioz, color_pelo, gris).
atributo(berlioz, pelo, corto).
atributo(berlioz, es_magico, no).
atributo(berlioz, color_vestimenta, na).
atributo(berlioz, vive_en, otro).
atributo(berlioz, genero, masculino).
atributo(berlioz, habla, si).

atributo(toulouse, especie, animal).
atributo(toulouse, es_villano, no).
atributo(toulouse, es_protagonista, no).
atributo(toulouse, color_pelo, naranja).
atributo(toulouse, pelo, corto).
atributo(toulouse, es_magico, no).
atributo(toulouse, color_vestimenta, na).
atributo(toulouse, vive_en, otro).
atributo(toulouse, genero, masculino).
atributo(toulouse, habla, si).

atributo(bambi, especie, animal).
atributo(bambi, es_villano, no).
atributo(bambi, es_protagonista, si).
atributo(bambi, color_pelo, ninguno).
atributo(bambi, pelo, sin_pelo).
atributo(bambi, es_magico, no).
atributo(bambi, color_vestimenta, cafe).
atributo(bambi, vive_en, bosque).
atributo(bambi, genero, masculino).
atributo(bambi, habla, si).

atributo(thumper, especie, animal).
atributo(thumper, es_villano, no).
atributo(thumper, es_protagonista, no).
atributo(thumper, color_pelo, gris).
atributo(thumper, pelo, corto).
atributo(thumper, es_magico, no).
atributo(thumper, color_vestimenta, na).
atributo(thumper, vive_en, bosque).
atributo(thumper, genero, masculino).
atributo(thumper, habla, si).

atributo(flower, especie, animal).
atributo(flower, es_villano, no).
atributo(flower, es_protagonista, no).
atributo(flower, color_pelo, negro).
atributo(flower, pelo, corto).
atributo(flower, es_magico, no).
atributo(flower, color_vestimenta, na).
atributo(flower, vive_en, bosque).
atributo(flower, genero, masculino).
atributo(flower, habla, si).

atributo(belle, especie, humano).
atributo(belle, es_villano, no).
atributo(belle, es_protagonista, si).
atributo(belle, color_pelo, cafe).
atributo(belle, pelo, largo).
atributo(belle, es_magico, no).
atributo(belle, color_vestimenta, azul).
atributo(belle, vive_en, castillo).
atributo(belle, genero, femenino).
atributo(belle, habla, si).

atributo(beast, especie, ser_magico).
atributo(beast, es_villano, no).
atributo(beast, es_protagonista, si).
atributo(beast, color_pelo, cafe).
atributo(beast, pelo, largo).
atributo(beast, es_magico, si).
atributo(beast, color_vestimenta, azul).
atributo(beast, vive_en, castillo).
atributo(beast, genero, masculino).
atributo(beast, habla, si).

atributo(cogsworth, especie, objeto).
atributo(cogsworth, es_villano, no).
atributo(cogsworth, es_protagonista, no).
atributo(cogsworth, color_pelo, ninguno).
atributo(cogsworth, pelo, sin_pelo).
atributo(cogsworth, es_magico, si).
atributo(cogsworth, color_vestimenta, cafe).
atributo(cogsworth, vive_en, castillo).
atributo(cogsworth, genero, masculino).
atributo(cogsworth, habla, si).

atributo(lumiere, especie, objeto).
atributo(lumiere, es_villano, no).
atributo(lumiere, es_protagonista, no).
atributo(lumiere, color_pelo, ninguno).
atributo(lumiere, pelo, sin_pelo).
atributo(lumiere, es_magico, si).
atributo(lumiere, color_vestimenta, amarillo).
atributo(lumiere, vive_en, castillo).
atributo(lumiere, genero, masculino).
atributo(lumiere, habla, si).

atributo(mrs_potts, especie, objeto).
atributo(mrs_potts, es_villano, no).
atributo(mrs_potts, es_protagonista, no).
atributo(mrs_potts, color_pelo, ninguno).
atributo(mrs_potts, pelo, sin_pelo).
atributo(mrs_potts, es_magico, si).
atributo(mrs_potts, color_vestimenta, blanco).
atributo(mrs_potts, vive_en, castillo).
atributo(mrs_potts, genero, femenino).
atributo(mrs_potts, habla, si).

atributo(elinor, especie, humano).
atributo(elinor, es_villano, no).
atributo(elinor, es_protagonista, no).
atributo(elinor, color_pelo, negro).
atributo(elinor, pelo, largo).
atributo(elinor, es_magico, si).
atributo(elinor, color_vestimenta, verde).
atributo(elinor, vive_en, castillo).
atributo(elinor, genero, femenino).
atributo(elinor, habla, si).

atributo(merida, especie, humano).
atributo(merida, es_villano, no).
atributo(merida, es_protagonista, si).
atributo(merida, color_pelo, naranja).
atributo(merida, pelo, largo).
atributo(merida, es_magico, no).
atributo(merida, color_vestimenta, azul).
atributo(merida, vive_en, castillo).
atributo(merida, genero, femenino).
atributo(merida, habla, si).

atributo(boys, especie, humano).
atributo(boys, es_villano, no).
atributo(boys, es_protagonista, no).
atributo(boys, color_pelo, naranja).
atributo(boys, pelo, corto).
atributo(boys, es_magico, no).
atributo(boys, color_vestimenta, azul).
atributo(boys, vive_en, castillo).
atributo(boys, genero, masculino).
atributo(boys, habla, no).

atributo(mcqueen, especie, objeto).
atributo(mcqueen, es_villano, no).
atributo(mcqueen, es_protagonista, si).
atributo(mcqueen, color_pelo, ninguno).
atributo(mcqueen, pelo, sin_pelo).
atributo(mcqueen, es_magico, no).
atributo(mcqueen, color_vestimenta, rojo).
atributo(mcqueen, vive_en, otro).
atributo(mcqueen, genero, masculino).
atributo(mcqueen, habla, si).

atributo(sally, especie, objeto).
atributo(sally, es_villano, no).
atributo(sally, es_protagonista, si).
atributo(sally, color_pelo, ninguno).
atributo(sally, pelo, sin_pelo).
atributo(sally, es_magico, no).
atributo(sally, color_vestimenta, azul).
atributo(sally, vive_en, otro).
atributo(sally, genero, femenino).
atributo(sally, habla, si).

atributo(flora, especie, ser_magico).
atributo(flora, es_villano, no).
atributo(flora, es_protagonista, no).
atributo(flora, color_pelo, gris).
atributo(flora, pelo, corto).
atributo(flora, es_magico, si).
atributo(flora, color_vestimenta, rojo).
atributo(flora, vive_en, bosque).
atributo(flora, genero, femenino).

atributo(merriweather, especie, ser_magico).
atributo(merriweather, es_villano, no).
atributo(merriweather, es_protagonista, no).
atributo(merriweather, color_pelo, negro).
atributo(merriweather, pelo, corto).
atributo(merriweather, es_magico, si).
atributo(merriweather, color_vestimenta, azul).
atributo(merriweather, vive_en, bosque).
atributo(merriweather, genero, femenino).

atributo(snow_white, especie, humano).
atributo(snow_white, es_villano, no).
atributo(snow_white, es_protagonista, si).
atributo(snow_white, color_pelo, negro).
atributo(snow_white, pelo, corto).
atributo(snow_white, es_magico, no).
atributo(snow_white, color_vestimenta, amarillo).
atributo(snow_white, vive_en, bosque).
atributo(snow_white, genero, femenino).

atributo(doc, especie, ser_magico).
atributo(doc, es_villano, no).
atributo(doc, es_protagonista, no).
atributo(doc, color_pelo, blanco).
atributo(doc, pelo, corto).
atributo(doc, es_magico, no).
atributo(doc, color_vestimenta, naranja).
atributo(doc, vive_en, bosque).
atributo(doc, genero, masculino).

atributo(dopey, especie, ser_magico).
atributo(dopey, es_villano, no).
atributo(dopey, es_protagonista, no).
atributo(dopey, color_pelo, blanco).
atributo(dopey, pelo, corto).
atributo(dopey, es_magico, no).
atributo(dopey, color_vestimenta, verde).
atributo(dopey, vive_en, bosque).
atributo(dopey, genero, masculino).

atributo(sleepy, especie, ser_magico).
atributo(sleepy, es_villano, no).
atributo(sleepy, es_protagonista, no).
atributo(sleepy, color_pelo, blanco).
atributo(sleepy, pelo, corto).
atributo(sleepy, es_magico, no).
atributo(sleepy, color_vestimenta, cafe).
atributo(sleepy, vive_en, bosque).
atributo(sleepy, genero, masculino).

atributo(sneezy, especie, ser_magico).
atributo(sneezy, es_villano, no).
atributo(sneezy, es_protagonista, no).
atributo(sneezy, color_pelo, blanco).
atributo(sneezy, pelo, corto).
atributo(sneezy, es_magico, no).
atributo(sneezy, color_vestimenta, amarillo).
atributo(sneezy, vive_en, bosque).
atributo(sneezy, genero, masculino).

atributo(happy, especie, ser_magico).
atributo(happy, es_villano, no).
atributo(happy, es_protagonista, no).
atributo(happy, color_pelo, blanco).
atributo(happy, pelo, corto).
atributo(happy, es_magico, no).
atributo(happy, color_vestimenta, azul).
atributo(happy, vive_en, bosque).
atributo(happy, genero, masculino).

atributo(bashful, especie, ser_magico).
atributo(bashful, es_villano, no).
atributo(bashful, es_protagonista, no).
atributo(bashful, color_pelo, blanco).
atributo(bashful, pelo, largo).
atributo(bashful, es_magico, no).
atributo(bashful, color_vestimenta, cafe).
atributo(bashful, vive_en, bosque).
atributo(bashful, genero, masculino).

atributo(grumpy, especie, ser_magico).
atributo(grumpy, es_villano, no).
atributo(grumpy, es_protagonista, no).
atributo(grumpy, color_pelo, blanco).
atributo(grumpy, pelo, corto).
atributo(grumpy, es_magico, no).
atributo(grumpy, color_vestimenta, rojo).
atributo(grumpy, vive_en, bosque).
atributo(grumpy, genero, masculino).

atributo(rapunzel, especie, humano).
atributo(rapunzel, es_villano, no).
atributo(rapunzel, es_protagonista, si).
atributo(rapunzel, color_pelo, rubio).
atributo(rapunzel, pelo, largo).
atributo(rapunzel, es_magico, si).
atributo(rapunzel, color_vestimenta, morado).
atributo(rapunzel, vive_en, bosque).
atributo(rapunzel, genero, femenino).

atributo(eugene, especie, humano).
atributo(eugene, es_villano, no).
atributo(eugene, es_protagonista, no).
atributo(eugene, color_pelo, cafe).
atributo(eugene, pelo, corto).
atributo(eugene, es_magico, no).
atributo(eugene, color_vestimenta, azul).
atributo(eugene, vive_en, ciudad).
atributo(eugene, genero, masculino).

atributo(tarzan, especie, humano).
atributo(tarzan, es_villano, no).
atributo(tarzan, es_protagonista, si).
atributo(tarzan, color_pelo, cafe).
atributo(tarzan, pelo, largo).
atributo(tarzan, es_magico, no).
atributo(tarzan, color_vestimenta, cafe).
atributo(tarzan, vive_en, bosque).
atributo(tarzan, genero, masculino).

atributo(jane, especie, humano).
atributo(jane, es_villano, no).
atributo(jane, es_protagonista, no).
atributo(jane, color_pelo, cafe).
atributo(jane, pelo, largo).
atributo(jane, es_magico, no).
atributo(jane, color_vestimenta, amarillo).
atributo(jane, vive_en, ciudad).
atributo(jane, genero, femenino).

atributo(woody, especie, objeto).
atributo(woody, es_villano, no).
atributo(woody, es_protagonista, si).
atributo(woody, color_pelo, cafe).
atributo(woody, pelo, corto).
atributo(woody, es_magico, no).
atributo(woody, color_vestimenta, amarillo).
atributo(woody, vive_en, ciudad).
atributo(woody, genero, masculino).

atributo(dash, especie, humano).
atributo(dash, es_villano, no).
atributo(dash, es_protagonista, si).
atributo(dash, color_pelo, rubio).
atributo(dash, pelo, corto).
atributo(dash, es_magico, si).
atributo(dash, color_vestimenta, rojo).
atributo(dash, vive_en, ciudad).
atributo(dash, genero, masculino).

atributo(jack_jack, especie, humano).
atributo(jack_jack, es_villano, no).
atributo(jack_jack, es_protagonista, no).
atributo(jack_jack, color_pelo, rubio).
atributo(jack_jack, pelo, corto).
atributo(jack_jack, es_magico, si).
atributo(jack_jack, color_vestimenta, rojo).
atributo(jack_jack, vive_en, ciudad).
atributo(jack_jack, genero, masculino).

atributo(mowgli, especie, humano).
atributo(mowgli, es_villano, no).
atributo(mowgli, es_protagonista, si).
atributo(mowgli, color_pelo, negro).
atributo(mowgli, pelo, corto).
atributo(mowgli, es_magico, no).
atributo(mowgli, color_vestimenta, rojo).
atributo(mowgli, vive_en, bosque).
atributo(mowgli, genero, masculino).

atributo(baloo, especie, animal).
atributo(baloo, es_villano, no).
atributo(baloo, es_protagonista, si).
atributo(baloo, color_pelo, gris).
atributo(baloo, pelo, corto).
atributo(baloo, es_magico, no).
atributo(baloo, color_vestimenta, na).
atributo(baloo, vive_en, bosque).
atributo(baloo, genero, masculino).

atributo(bagheera, especie, animal).
atributo(bagheera, es_villano, no).
atributo(bagheera, es_protagonista, no).
atributo(bagheera, color_pelo, negro).
atributo(bagheera, pelo, corto).
atributo(bagheera, es_magico, no).
atributo(bagheera, color_vestimenta, na).
atributo(bagheera, vive_en, bosque).
atributo(bagheera, genero, masculino).

atributo(tramp, especie, animal).
atributo(tramp, es_villano, no).
atributo(tramp, es_protagonista, si).
atributo(tramp, color_pelo, gris).
atributo(tramp, pelo, corto).
atributo(tramp, es_magico, no).
atributo(tramp, color_vestimenta, rojo).
atributo(tramp, vive_en, ciudad).
atributo(tramp, genero, masculino).

atributo(lady, especie, animal).
atributo(lady, es_villano, no).
atributo(lady, es_protagonista, si).
atributo(lady, color_pelo, naranja).
atributo(lady, pelo, largo).
atributo(lady, es_magico, no).
atributo(lady, color_vestimenta, azul).
atributo(lady, vive_en, ciudad).
atributo(lady, genero, femenino).

atributo(lilo, especie, humano).
atributo(lilo, es_villano, no).
atributo(lilo, es_protagonista, si).
atributo(lilo, color_pelo, negro).
atributo(lilo, pelo, largo).
atributo(lilo, es_magico, no).
atributo(lilo, color_vestimenta, rojo).
atributo(lilo, vive_en, ciudad).
atributo(lilo, genero, femenino).

atributo(stitch, especie, animal).
atributo(stitch, es_villano, no).
atributo(stitch, es_protagonista, si).
atributo(stitch, color_pelo, azul).
atributo(stitch, pelo, corto).
atributo(stitch, es_magico, no).
atributo(stitch, color_vestimenta, na).
atributo(stitch, vive_en, otro).
atributo(stitch, genero, masculino).

atributo(simba, especie, animal).
atributo(simba, es_villano, no).
atributo(simba, es_protagonista, si).
atributo(simba, color_pelo, rubio).
atributo(simba, pelo, corto).
atributo(simba, es_magico, no).
atributo(simba, color_vestimenta, na).
atributo(simba, vive_en, desierto).
atributo(simba, genero, masculino).

atributo(nala, especie, animal).
atributo(nala, es_villano, no).
atributo(nala, es_protagonista, no).
atributo(nala, color_pelo, rubio).
atributo(nala, pelo, corto).
atributo(nala, es_magico, no).
atributo(nala, color_vestimenta, na).
atributo(nala, vive_en, desierto).
atributo(nala, genero, masculino).

atributo(timon, especie, animal).
atributo(timon, es_villano, no).
atributo(timon, es_protagonista, no).
atributo(timon, color_pelo, naranja).
atributo(timon, pelo, corto).
atributo(timon, es_magico, no).
atributo(timon, color_vestimenta, na).
atributo(timon, vive_en, desierto).
atributo(timon, genero, masculino).

atributo(pumbaa, especie, animal).
atributo(pumbaa, es_villano, no).
atributo(pumbaa, es_protagonista, no).
atributo(pumbaa, color_pelo, rojo).
atributo(pumbaa, pelo, corto).
atributo(pumbaa, es_magico, no).
atributo(pumbaa, color_vestimenta, na).
atributo(pumbaa, vive_en, desierto).
atributo(pumbaa, genero, masculino).

atributo(rafiki, especie, animal).
atributo(rafiki, es_villano, no).
atributo(rafiki, es_protagonista, no).
atributo(rafiki, color_pelo, gris).
atributo(rafiki, pelo, corto).
atributo(rafiki, es_magico, no).
atributo(rafiki, color_vestimenta, na).
atributo(rafiki, vive_en, desierto).
atributo(rafiki, genero, masculino).

atributo(zazu, especie, animal).
atributo(zazu, es_villano, no).
atributo(zazu, es_protagonista, no).
atributo(zazu, color_pelo, azul).
atributo(zazu, pelo, corto).
atributo(zazu, es_magico, no).
atributo(zazu, color_vestimenta, na).
atributo(zazu, vive_en, desierto).
atributo(zazu, genero, masculino).

atributo(ariel, especie, humano).
atributo(ariel, es_villano, no).
atributo(ariel, es_protagonista, si).
atributo(ariel, color_pelo, rojo).
atributo(ariel, pelo, largo).
atributo(ariel, es_magico, no).
atributo(ariel, color_vestimenta, rosa).
atributo(ariel, vive_en, castillo).
atributo(ariel, genero, femenino).

atributo(eric, especie, humano).
atributo(eric, es_villano, no).
atributo(eric, es_protagonista, si).
atributo(eric, color_pelo, negro).
atributo(eric, pelo, corto).
atributo(eric, es_magico, no).
atributo(eric, color_vestimenta, blanco).
atributo(eric, vive_en, castillo).
atributo(eric, genero, masculino).

atributo(scuttle, especie, animal).
atributo(scuttle, es_villano, no).
atributo(scuttle, es_protagonista, no).
atributo(scuttle, color_pelo, blanco).
atributo(scuttle, pelo, corto).
atributo(scuttle, es_magico, no).
atributo(scuttle, color_vestimenta, na).
atributo(scuttle, vive_en, oceano).
atributo(scuttle, genero, masculino).

atributo(flounder, especie, animal).
atributo(flounder, es_villano, no).
atributo(flounder, es_protagonista, no).
atributo(flounder, color_pelo, azul).
atributo(flounder, pelo, corto).
atributo(flounder, es_magico, no).
atributo(flounder, color_vestimenta, amarillo).
atributo(flounder, vive_en, oceano).
atributo(flounder, genero, masculino).

atributo(sebastian, especie, animal).
atributo(sebastian, es_villano, no).
atributo(sebastian, es_protagonista, no).
atributo(sebastian, color_pelo, rojo).
atributo(sebastian, pelo, corto).
atributo(sebastian, es_magico, no).
atributo(sebastian, color_vestimenta, rojo).
atributo(sebastian, vive_en, oceano).
atributo(sebastian, genero, masculino).

atributo(boo, especie, humano).
atributo(boo, es_villano, no).
atributo(boo, es_protagonista, si).
atributo(boo, color_pelo, negro).
atributo(boo, pelo, corto).
atributo(boo, es_magico, no).
atributo(boo, color_vestimenta, morado).
atributo(boo, vive_en, otro).
atributo(boo, genero, femenino).

atributo(mike, especie, animal).
atributo(mike, es_villano, no).
atributo(mike, es_protagonista, si).
atributo(mike, color_pelo, ninguno).
atributo(mike, pelo, sin_pelo).
atributo(mike, es_magico, no).
atributo(mike, color_vestimenta, verde).
atributo(mike, vive_en, otro).
atributo(mike, genero, masculino).

atributo(sully, especie, animal).
atributo(sully, es_villano, no).
atributo(sully, es_protagonista, si).
atributo(sully, color_pelo, ninguno).
atributo(sully, pelo, corto).
atributo(sully, es_magico, no).
atributo(sully, color_vestimenta, azul).
atributo(sully, vive_en, otro).
atributo(sully, genero, masculino).

atributo(mulan, especie, humano).
atributo(mulan, es_villano, no).
atributo(mulan, es_protagonista, si).
atributo(mulan, color_pelo, negro).
atributo(mulan, pelo, largo).
atributo(mulan, es_magico, no).
atributo(mulan, color_vestimenta, rosa).
atributo(mulan, vive_en, ciudad).
atributo(mulan, genero, femenino).

atributo(shang, especie, humano).
atributo(shang, es_villano, no).
atributo(shang, es_protagonista, si).
atributo(shang, color_pelo, negro).
atributo(shang, pelo, corto).
atributo(shang, es_magico, no).
atributo(shang, color_vestimenta, cafe).
atributo(shang, vive_en, otro).
atributo(shang, genero, masculino).

atributo(mushu, especie, ser_magico).
atributo(mushu, es_villano, no).
atributo(mushu, es_protagonista, si).
atributo(mushu, color_pelo, ninguno).
atributo(mushu, pelo, sin_pelo).
atributo(mushu, es_magico, si).
atributo(mushu, color_vestimenta, rojo).
atributo(mushu, vive_en, otro).
atributo(mushu, genero, masculino).

atributo(john, especie, humano).
atributo(john, es_villano, no).
atributo(john, es_protagonista, no).
atributo(john, color_pelo, cafe).
atributo(john, pelo, corto).
atributo(john, es_magico, no).
atributo(john, color_vestimenta, blanco).
atributo(john, vive_en, ciudad).
atributo(john, genero, masculino).

atributo(michael, especie, humano).
atributo(michael, es_villano, no).
atributo(michael, es_protagonista, no).
atributo(michael, color_pelo, naranja).
atributo(michael, pelo, corto).
atributo(michael, es_magico, no).
atributo(michael, color_vestimenta, rosa).
atributo(michael, vive_en, ciudad).
atributo(michael, genero, masculino).

atributo(peter_pan, especie, humano).
atributo(peter_pan, es_villano, no).
atributo(peter_pan, es_protagonista, si).
atributo(peter_pan, color_pelo, rojo).
atributo(peter_pan, pelo, corto).
atributo(peter_pan, es_magico, si).
atributo(peter_pan, color_vestimenta, verde).
atributo(peter_pan, vive_en, otro).
atributo(peter_pan, genero, masculino).

atributo(wendy, especie, humano).
atributo(wendy, es_villano, no).
atributo(wendy, es_protagonista, si).
atributo(wendy, color_pelo, cafe).
atributo(wendy, pelo, largo).
atributo(wendy, es_magico, no).
atributo(wendy, color_vestimenta, azul).
atributo(wendy, vive_en, ciudad).
atributo(wendy, genero, femenino).

atributo(mater, especie, objeto).
atributo(mater, es_villano, no).
atributo(mater, es_protagonista, si).
atributo(mater, color_pelo, ninguno).
atributo(mater, pelo, sin_pelo).
atributo(mater, es_magico, no).
atributo(mater, color_vestimenta, cafe).
atributo(mater, vive_en, otro).
atributo(mater, genero, masculino).

atributo(cinderella, especie, humano).
atributo(cinderella, es_villano, no).
atributo(cinderella, es_protagonista, si).
atributo(cinderella, color_pelo, rubio).
atributo(cinderella, pelo, largo).
atributo(cinderella, es_magico, no).
atributo(cinderella, color_vestimenta, azul).
atributo(cinderella, vive_en, castillo).
atributo(cinderella, genero, femenino).

atributo(fairy_godmother, especie, ser_magico).
atributo(fairy_godmother, es_villano, no).
atributo(fairy_godmother, es_protagonista, no).
atributo(fairy_godmother, color_pelo, gris).
atributo(fairy_godmother, pelo, corto).
atributo(fairy_godmother, es_magico, si).
atributo(fairy_godmother, color_vestimenta, morado).
atributo(fairy_godmother, vive_en, otro).
atributo(fairy_godmother, genero, femenino).

atributo(jaq, especie, animal).
atributo(jaq, es_villano, no).
atributo(jaq, es_protagonista, no).
atributo(jaq, color_pelo, cafe).
atributo(jaq, pelo, corto).
atributo(jaq, es_magico, no).
atributo(jaq, color_vestimenta, rojo).
atributo(jaq, vive_en, castillo).
atributo(jaq, genero, masculino).

atributo(gus, especie, animal).
atributo(gus, es_villano, no).
atributo(gus, es_protagonista, no).
atributo(gus, color_pelo, cafe).
atributo(gus, pelo, corto).
atributo(gus, es_magico, no).
atributo(gus, color_vestimenta, verde).
atributo(gus, vive_en, castillo).
atributo(gus, genero, masculino).

atributo(dumbo, especie, animal).
atributo(dumbo, es_villano, no).
atributo(dumbo, es_protagonista, si).
atributo(dumbo, color_pelo, ninguno).
atributo(dumbo, pelo, sin_pelo).
atributo(dumbo, es_magico, no).
atributo(dumbo, color_vestimenta, na).
atributo(dumbo, vive_en, otro).
atributo(dumbo, genero, masculino).

atributo(hercules, especie, humano).
atributo(hercules, es_villano, no).
atributo(hercules, es_protagonista, si).
atributo(hercules, color_pelo, naranja).
atributo(hercules, pelo, corto).
atributo(hercules, es_magico, no).
atributo(hercules, color_vestimenta, naranja).
atributo(hercules, vive_en, otro).
atributo(hercules, genero, masculino).

atributo(pegasus, especie, ser_magico).
atributo(pegasus, es_villano, no).
atributo(pegasus, es_protagonista, no).
atributo(pegasus, color_pelo, azul).
atributo(pegasus, pelo, corto).
atributo(pegasus, es_magico, si).
atributo(pegasus, color_vestimenta, blanco).
atributo(pegasus, vive_en, otro).
atributo(pegasus, genero, masculino).

atributo(meg, especie, humano).
atributo(meg, es_villano, no).
atributo(meg, es_protagonista, si).
atributo(meg, color_pelo, cafe).
atributo(meg, pelo, largo).
atributo(meg, es_magico, no).
atributo(meg, color_vestimenta, morado).
atributo(meg, vive_en, otro).
atributo(meg, genero, femenino).

atributo(phil, especie, ser_magico).
atributo(phil, es_villano, no).
atributo(phil, es_protagonista, no).
atributo(phil, color_pelo, naranja).
atributo(phil, pelo, sin_pelo).
atributo(phil, es_magico, no).
atributo(phil, color_vestimenta, na).
atributo(phil, vive_en, otro).
atributo(phil, genero, masculino).

atributo(quasimodo, especie, humano).
atributo(quasimodo, es_villano, no).
atributo(quasimodo, es_protagonista, si).
atributo(quasimodo, color_pelo, rojo).
atributo(quasimodo, pelo, corto).
atributo(quasimodo, es_magico, no).
atributo(quasimodo, color_vestimenta, verde).
atributo(quasimodo, vive_en, ciudad).
atributo(quasimodo, genero, masculino).

atributo(esmeralda, especie, humano).
atributo(esmeralda, es_villano, no).
atributo(esmeralda, es_protagonista, si).
atributo(esmeralda, color_pelo, negro).
atributo(esmeralda, pelo, largo).
atributo(esmeralda, es_magico, no).
atributo(esmeralda, color_vestimenta, blanco).
atributo(esmeralda, vive_en, ciudad).
atributo(esmeralda, genero, femenino).

atributo(mr_incredible, especie, humano).
atributo(mr_incredible, es_villano, no).
atributo(mr_incredible, es_protagonista, si).
atributo(mr_incredible, color_pelo, rubio).
atributo(mr_incredible, pelo, corto).
atributo(mr_incredible, es_magico, si).
atributo(mr_incredible, color_vestimenta, rojo).
atributo(mr_incredible, vive_en, ciudad).
atributo(mr_incredible, genero, masculino).

atributo(elastigirl, especie, humano).
atributo(elastigirl, es_villano, no).
atributo(elastigirl, es_protagonista, si).
atributo(elastigirl, color_pelo, cafe).
atributo(elastigirl, pelo, corto).
atributo(elastigirl, es_magico, si).
atributo(elastigirl, color_vestimenta, rojo).
atributo(elastigirl, vive_en, ciudad).
atributo(elastigirl, genero, femenino).

atributo(violet, especie, humano).
atributo(violet, es_villano, no).
atributo(violet, es_protagonista, si).
atributo(violet, color_pelo, negro).
atributo(violet, pelo, largo).
atributo(violet, es_magico, si).
atributo(violet, color_vestimenta, rojo).
atributo(violet, vive_en, ciudad).
atributo(violet, genero, femenino).

