name: Validar personajes.csv

on:
  pull_request:
    paths:
      - personajes.csv

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Correr generate.py
        run: python3 generate.py
